# Our build command used to include "bundle" to support Asciidoc format,
# making sure Asciidoctor gets installed, now Netlify seems to take care of it
[build]
    publish = "public"
    command = "chmod +x build.sh && ./build.sh"
    HUGO_ENABLEGITINFO = "true"
    # RUBY_VERSION = "2.6.2" is set as environment variable in Netlify UI, Deploy settings

# The Production Context applies to the branch you have configured as main branch to deploy:
[context.production.environment]
    HUGO_VERSION = "0.123.1"
    HUGO_ENV = "production"

# The Deploy Preview Context applies to every Deploy Preview you create:
[context.deploy-preview]
    command = "chmod +x build.sh && ./build.sh -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
    HUGO_VERSION = "0.123.1"

[context.branch-deploy]
    command = "chmod +x build.sh && ./build.sh -b $DEPLOY_PRIME_URL"

# The Branch Deploy Context applies to all non-master branches deployed, whether they are in a Deploy Preview or not:
[context.branch-deploy.environment]
    HUGO_VERSION = "0.123.1"

[[redirects]]
    from = "/guides/guide/*"
    to = "/guides/:splat"
    status = 301

[[redirects]]
    from = "/pricing"
    to = "/cloud/pricing/"
    status = 301

[[redirects]]
    from = "/community-champions/joshua-boylan-long/"
    to = "/community-champions/josh-long/"
    status = 301

[[redirects]]
    from = "/desktop/authorized/"
    to = "https://app.testcontainers.cloud/api/auth/login"
    status = 302